"""Python backend — compile ASG nodes to standalone Python code.

ASG → Python source string. The generated code, when executed, produces the
same OS outcome as direct execution through the interpreter.

This is distinct from the interpreter (which IS Python executing the ASG
directly). The Python backend generates a *source string* — code that could
be saved to a .py file and run independently. This proves the ASG is
target-independent: the same graph compiles to both shell and Python.

v03.1: Added GlobFiles + ForEachFile compilation (Python for-loop with fnmatch).
v03.2: Added SetVar + PrintVar compilation (variable capture/emit with dict).
"""

from __future__ import annotations

from asg import (
    ASGNode, CreateFile, ReadFile, AppendFile, CountLines, CopyFile,
    MakeDirectory, MoveFile, ListFiles, FindFiles, DeleteFile, Conditional,
    CountWords, SortLines, HeadLines, SumNumbers, ExtractPattern,
    GlobFiles, ForEachFile,
    SetVar, PrintVar,
    ReplaceText, TransformCase, UniqueLines, ReverseLines,
    TailLines, FilterLines, IfVar,
)


def compile_to_python(nodes: list[ASGNode]) -> str:
    """Compile a list of ASG nodes into a standalone Python script string."""
    lines = [
        "#!/usr/bin/env python3",
        "# Auto-generated by python_backend.compile_to_python()",
        "# Source: ASG → Python",
        "import os",
        "import sys",
        "",
        "_vars = {}",
        "",
        "",
        "def main():",
    ]
    indent = "    "
    body = _compile_nodes(nodes, indent)
    if not body.strip():
        body = f"{indent}pass"
    lines.append(body)
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    main()")
    return '\n'.join(lines)


def _compile_nodes(nodes: list[ASGNode], indent: str) -> str:
    """Compile a list of nodes at the given indentation level."""
    lines = []
    for i, node in enumerate(nodes):
        code = _compile_node(node, indent)
        lines.append(code)
    return '\n'.join(lines)


def _compile_node(node: ASGNode, indent: str) -> str:
    """Compile a single node to Python code at the given indent."""

    def ind(code: str) -> str:
        """Apply indent to a multi-line block."""
        return '\n'.join(indent + line if line.strip() else line for line in code.split('\n'))

    match node:


        case ReplaceText(name=name, old=old, new=new):
            name_r = repr(name)
            old_r = repr(old)
            new_r = repr(new)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        _lines = [l.rstrip('\\n') for l in _f.readlines() if l.strip()]\n"
                f"    sys.stdout.write(' '.join(l.replace({old_r}, {new_r}) for l in _lines))"
            )

        case TransformCase(name=name, mode=mode):
            name_r = repr(name)
            mode_r = repr(mode)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        _lines = [l.rstrip('\\n') for l in _f.readlines() if l.strip()]\n"
                f"    _m = {mode_r}\n"
                f"    _t = [l.upper() if _m == 'upper' else l.lower() if _m == 'lower' else l.title() for l in _lines]\n"
                f"    sys.stdout.write(' '.join(_t))"
            )

        case UniqueLines(name=name):
            name_r = repr(name)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        _lines = [l.rstrip('\\n') for l in _f.readlines() if l.strip()]\n"
                f"    _seen = set()\n"
                f"    _uniq = []\n"
                f"    for _l in _lines:\n"
                f"        if _l not in _seen:\n"
                f"            _seen.add(_l)\n"
                f"            _uniq.append(_l)\n"
                f"    sys.stdout.write(' '.join(_uniq))"
            )

        case ReverseLines(name=name):
            name_r = repr(name)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        _lines = [l.rstrip('\\n') for l in _f.readlines() if l.strip()]\n"
                f"    sys.stdout.write(' '.join(reversed(_lines)))"
            )


        # --- v03.4: Tail, Filter, IfVar ---

        case TailLines(name=name, count=count):
            name_r = repr(name)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        _lines = [l.rstrip('\\n') for l in _f.readlines() if l.strip()]\n"
                f"    sys.stdout.write(' '.join(_lines[-{count}:]))"
            )

        case FilterLines(name=name, pattern=pattern):
            name_r = repr(name)
            pat_r = repr(pattern)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        _lines = [l.rstrip('\\n') for l in _f.readlines() if l.strip()]\n"
                f"    sys.stdout.write(' '.join(l for l in _lines if {pat_r} not in l))"
            )

        case IfVar(var_name=var_name, op=op, threshold=threshold,
                   then_branch=then_branch, else_branch=else_branch):
            var_r = repr(var_name)
            op_r = repr(op)
            # Compile then/else branches at extra indent
            inner_indent = indent + "    "
            then_code = _compile_nodes(list(then_branch), inner_indent)
            else_code = _compile_nodes(list(else_branch), inner_indent)
            return ind(
                f"_val = int(_vars.get({var_r}, '0') or '0')\n"
                f"_ops = {{'>': _val > {threshold}, '<': _val < {threshold},\n"
                f"         '>=': _val >= {threshold}, '<=': _val <= {threshold},\n"
                f"         '==': _val == {threshold}, '!=': _val != {threshold}}}\n"
                f"if _ops.get({op_r}, False):\n"
                f"{then_code}\n"
                f"else:\n"
                f"{else_code}"
            )

        # --- v03.2: Variable binding ---

        case SetVar(var_name=var_name, source_node=source_node):
            var_r = repr(var_name)
            # Capture stdout from source_node into _vars dict
            inner_indent = indent + "    "
            # We compile the source node, then wrap it in a StringIO capture
            source_code = _compile_node(source_node, inner_indent)
            block = (
                f"import io as _io\n"
                f"_old = sys.stdout\n"
                f"_buf = _io.StringIO()\n"
                f"sys.stdout = _buf\n"
                f"try:\n"
                f"{source_code}\n"
                f"finally:\n"
                f"    sys.stdout = _old\n"
                f"_vars[{var_r}] = _buf.getvalue().rstrip('\\n')"
            )
            return ind(block)

        case PrintVar(var_name=var_name):
            var_r = repr(var_name)
            return ind(f"sys.stdout.write(_vars.get({var_r}, ''))")

        case CreateFile(name=name, content=content):
            name_r = repr(name)
            content_r = repr(content)
            return ind(
                f"if os.path.exists({name_r}):\n"
                f"    sys.stdout.write('REFUSED')\n"
                f"else:\n"
                f"    with open({name_r}, 'w') as _f:\n"
                f"        _f.write({content_r})"
            )

        case ReadFile(name=name):
            name_r = repr(name)
            return ind(
                f"if os.path.exists({name_r}):\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        _content = _f.read()\n"
                f"    sys.stdout.write(_content.replace('\\n', ' '))"
            )

        case AppendFile(text=text, name=name):
            text_r = repr(text)
            name_r = repr(name)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('REFUSED')\n"
                f"else:\n"
                f"    with open({name_r}, 'a') as _f:\n"
                f"        _f.write('\\n' + {text_r})"
            )

        case CountLines(name=name):
            name_r = repr(name)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('0')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        sys.stdout.write(str(len(_f.readlines())))"
            )

        case CountWords(name=name):
            name_r = repr(name)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('0')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        sys.stdout.write(str(len(_f.read().split())))"
            )

        case SortLines(name=name):
            name_r = repr(name)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        _lines = [l.rstrip('\\n') for l in _f.readlines() if l.strip()]\n"
                f"    sys.stdout.write(' '.join(sorted(_lines)))"
            )

        case HeadLines(name=name, count=count):
            name_r = repr(name)
            count_r = repr(count)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        _lines = [l.rstrip('\\n') for l in _f.readlines()]\n"
                f"    sys.stdout.write(' '.join(_lines[:{count_r}]))"
            )

        case SumNumbers(name=name):
            name_r = repr(name)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('0')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        _content = _f.read()\n"
                f"    import re as _re\n"
                f"    _nums = [int(x) for x in _re.findall(r'\\d+', _content)]\n"
                f"    sys.stdout.write(str(sum(_nums)))"
            )

        case ExtractPattern(name=name, pattern=pattern):
            name_r = repr(name)
            pattern_r = repr(pattern)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        _lines = [l.rstrip('\\n') for l in _f.readlines() if l.strip()]\n"
                f"    _matching = [l for l in _lines if {pattern_r} in l]\n"
                f"    sys.stdout.write(' '.join(_matching))"
            )

        case CopyFile(source=source, dest=dest):
            src_r = repr(source)
            dest_r = repr(dest)
            return ind(
                f"if not os.path.exists({src_r}) or os.path.exists({dest_r}):\n"
                f"    sys.stdout.write('REFUSED')\n"
                f"else:\n"
                f"    with open({src_r}, 'r') as _fs, open({dest_r}, 'w') as _fd:\n"
                f"        _fd.write(_fs.read())"
            )

        case MakeDirectory(name=name):
            name_r = repr(name)
            return ind(
                f"if os.path.exists({name_r}):\n"
                f"    sys.stdout.write('REFUSED')\n"
                f"else:\n"
                f"    os.makedirs({name_r}, exist_ok=False)"
            )

        case MoveFile(source=source, dest=dest):
            src_r = repr(source)
            dest_r = repr(dest)
            basename = source.split('/')[-1] if '/' in source else source
            return ind(
                f"if not os.path.exists({src_r}):\n"
                f"    sys.stdout.write('REFUSED')\n"
                f"else:\n"
                f"    _dest = os.path.join({dest_r}, {repr(basename)}) if os.path.isdir({dest_r}) else {dest_r}\n"
                f"    if os.path.exists(_dest):\n"
                f"        sys.stdout.write('REFUSED')\n"
                f"    else:\n"
                f"        os.rename({src_r}, _dest)"
            )

        case ListFiles(directory=directory):
            dir_r = repr(directory)
            return ind(
                f"if not os.path.isdir({dir_r}):\n"
                f"    sys.stdout.write('(empty)')\n"
                f"else:\n"
                f"    _files = sorted(f for f in os.listdir({dir_r}) if os.path.isfile(os.path.join({dir_r}, f)))\n"
                f"    sys.stdout.write(' '.join(_files) if _files else '(empty)')"
            )

        case FindFiles(text=text):
            text_r = repr(text)
            return ind(
                f"_matches = []\n"
                f"for _fname in os.listdir('.'):\n"
                f"    if not os.path.isfile(_fname):\n"
                f"        continue\n"
                f"    try:\n"
                f"        with open(_fname, 'r') as _f:\n"
                f"            if {text_r} in _f.read():\n"
                f"                _matches.append(_fname)\n"
                f"    except (OSError, UnicodeDecodeError):\n"
                f"        pass\n"
                f"sys.stdout.write(' '.join(sorted(_matches)) if _matches else '(none)')"
            )

        case DeleteFile(name=name, confirm=confirm):
            name_r = repr(name)
            if not confirm:
                return ind("sys.stdout.write('REFUSED')")
            return ind(
                f"if os.path.isfile({name_r}):\n"
                f"    os.remove({name_r})"
            )

        case Conditional(condition_file=condition_file,
                         then_branch=then_branch,
                         else_branch=else_branch):
            cond_r = repr(condition_file)
            then_code = _compile_nodes(then_branch, "    ")
            else_code = _compile_nodes(else_branch, "    ")
            block = (
                f"if os.path.exists({cond_r}):\n"
                f"{then_code}\n"
                f"else:\n"
                f"{else_code}"
            )
            return ind(block)

        # --- v03.1: Iteration nodes ---

        case GlobFiles(pattern=pattern):
            pat_r = repr(pattern)
            return ind(
                f"import fnmatch as _fnmatch\n"
                f"_glob_result = sorted(f for f in os.listdir('.') "
                f"if os.path.isfile(f) and _fnmatch.fnmatch(f, {pat_r}))\n"
                f"sys.stdout.write(' '.join(_glob_result) if _glob_result else '(none)')"
            )

        case ForEachFile(glob_pattern=glob_pattern,
                         body_template=body_template,
                         placeholder=placeholder):
            pat_r = repr(glob_pattern)
            inner_indent = indent + "    "
            lines = [
                f"import fnmatch as _fnmatch",
                f"_mk_files = sorted(f for f in os.listdir('.') "
                f"if os.path.isfile(f) and _fnmatch.fnmatch(f, {pat_r}))",
                f"for _mk_f in _mk_files:",
            ]
            for tmpl in body_template:
                code = _compile_node(tmpl, inner_indent)
                code = code.replace(placeholder, "' + _mk_f + '")
                lines.append(code)
            return '\n'.join(lines)

        case _:
            return ind("pass  # unknown node type")
