"""Python backend — compile ASG nodes to standalone Python code.

ASG → Python source string. The generated code, when executed, produces the
same OS outcome as direct execution through the interpreter.

This is distinct from the interpreter (which IS Python executing the ASG
directly). The Python backend generates a *source string* — code that could
be saved to a .py file and run independently. This proves the ASG is
target-independent: the same graph compiles to both shell and Python.

v03.1: Added GlobFiles + ForEachFile compilation (Python for-loop with fnmatch).
"""

from __future__ import annotations

from asg import (
    ASGNode, CreateFile, ReadFile, AppendFile, CountLines, CopyFile,
    MakeDirectory, MoveFile, ListFiles, FindFiles, DeleteFile, Conditional,
    CountWords, SortLines, HeadLines, SumNumbers, ExtractPattern,
    GlobFiles, ForEachFile,
)


def compile_to_python(nodes: list[ASGNode]) -> str:
    """Compile a list of ASG nodes into a standalone Python script string."""
    lines = [
        "#!/usr/bin/env python3",
        "# Auto-generated by python_backend.compile_to_python()",
        "# Source: ASG → Python",
        "import os",
        "import sys",
        "",
        "",
        "def main():",
    ]
    indent = "    "
    body = _compile_nodes(nodes, indent)
    if not body.strip():
        body = f"{indent}pass"
    lines.append(body)
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    main()")
    return '\n'.join(lines)


def _compile_nodes(nodes: list[ASGNode], indent: str) -> str:
    """Compile a list of nodes at the given indentation level."""
    lines = []
    for i, node in enumerate(nodes):
        code = _compile_node(node, indent)
        lines.append(code)
    return '\n'.join(lines)


def _compile_node(node: ASGNode, indent: str) -> str:
    """Compile a single node to Python code at the given indent."""

    def ind(code: str) -> str:
        """Apply indent to a multi-line block."""
        return '\n'.join(indent + line if line.strip() else line for line in code.split('\n'))

    match node:

        case CreateFile(name=name, content=content):
            name_r = repr(name)
            content_r = repr(content)
            return ind(
                f"if os.path.exists({name_r}):\n"
                f"    sys.stdout.write('REFUSED')\n"
                f"else:\n"
                f"    with open({name_r}, 'w') as _f:\n"
                f"        _f.write({content_r})"
            )

        case ReadFile(name=name):
            name_r = repr(name)
            return ind(
                f"if os.path.exists({name_r}):\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        _content = _f.read()\n"
                f"    sys.stdout.write(_content.replace('\\n', ' '))"
            )

        case AppendFile(text=text, name=name):
            text_r = repr(text)
            name_r = repr(name)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('REFUSED')\n"
                f"else:\n"
                f"    with open({name_r}, 'a') as _f:\n"
                f"        _f.write('\\n' + {text_r})"
            )

        case CountLines(name=name):
            name_r = repr(name)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('0')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        sys.stdout.write(str(len(_f.readlines())))"
            )

        case CountWords(name=name):
            name_r = repr(name)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('0')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        sys.stdout.write(str(len(_f.read().split())))"
            )

        case SortLines(name=name):
            name_r = repr(name)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        _lines = [l.rstrip('\\n') for l in _f.readlines() if l.strip()]\n"
                f"    sys.stdout.write(' '.join(sorted(_lines)))"
            )

        case HeadLines(name=name, count=count):
            name_r = repr(name)
            count_r = repr(count)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        _lines = [l.rstrip('\\n') for l in _f.readlines()]\n"
                f"    sys.stdout.write(' '.join(_lines[:{count_r}]))"
            )

        case SumNumbers(name=name):
            name_r = repr(name)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('0')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        _content = _f.read()\n"
                f"    import re as _re\n"
                f"    _nums = [int(x) for x in _re.findall(r'\\d+', _content)]\n"
                f"    sys.stdout.write(str(sum(_nums)))"
            )

        case ExtractPattern(name=name, pattern=pattern):
            name_r = repr(name)
            pattern_r = repr(pattern)
            return ind(
                f"if not os.path.exists({name_r}):\n"
                f"    sys.stdout.write('')\n"
                f"else:\n"
                f"    with open({name_r}, 'r') as _f:\n"
                f"        _lines = [l.rstrip('\\n') for l in _f.readlines() if l.strip()]\n"
                f"    _matching = [l for l in _lines if {pattern_r} in l]\n"
                f"    sys.stdout.write(' '.join(_matching))"
            )

        case CopyFile(source=source, dest=dest):
            src_r = repr(source)
            dest_r = repr(dest)
            return ind(
                f"if not os.path.exists({src_r}) or os.path.exists({dest_r}):\n"
                f"    sys.stdout.write('REFUSED')\n"
                f"else:\n"
                f"    with open({src_r}, 'r') as _fs, open({dest_r}, 'w') as _fd:\n"
                f"        _fd.write(_fs.read())"
            )

        case MakeDirectory(name=name):
            name_r = repr(name)
            return ind(
                f"if os.path.exists({name_r}):\n"
                f"    sys.stdout.write('REFUSED')\n"
                f"else:\n"
                f"    os.makedirs({name_r}, exist_ok=False)"
            )

        case MoveFile(source=source, dest=dest):
            src_r = repr(source)
            dest_r = repr(dest)
            basename = source.split('/')[-1] if '/' in source else source
            return ind(
                f"if not os.path.exists({src_r}):\n"
                f"    sys.stdout.write('REFUSED')\n"
                f"else:\n"
                f"    _dest = os.path.join({dest_r}, {repr(basename)}) if os.path.isdir({dest_r}) else {dest_r}\n"
                f"    if os.path.exists(_dest):\n"
                f"        sys.stdout.write('REFUSED')\n"
                f"    else:\n"
                f"        os.rename({src_r}, _dest)"
            )

        case ListFiles(directory=directory):
            dir_r = repr(directory)
            return ind(
                f"if not os.path.isdir({dir_r}):\n"
                f"    sys.stdout.write('(empty)')\n"
                f"else:\n"
                f"    _files = sorted(f for f in os.listdir({dir_r}) if os.path.isfile(os.path.join({dir_r}, f)))\n"
                f"    sys.stdout.write(' '.join(_files) if _files else '(empty)')"
            )

        case FindFiles(text=text):
            text_r = repr(text)
            return ind(
                f"_matches = []\n"
                f"for _fn in os.listdir('.'):\n"
                f"    if not os.path.isfile(_fn):\n"
                f"        continue\n"
                f"    try:\n"
                f"        with open(_fn, 'r') as _f:\n"
                f"            if {text_r} in _f.read():\n"
                f"                _matches.append(_fn)\n"
                f"    except (OSError, UnicodeDecodeError):\n"
                f"        continue\n"
                f"_matches.sort()\n"
                f"sys.stdout.write(' '.join(_matches) if _matches else '(none)')"
            )

        case DeleteFile(name=name, confirm=confirm):
            name_r = repr(name)
            if not confirm:
                return ind("sys.stdout.write('REFUSED')")
            return ind(
                f"if os.path.isfile({name_r}):\n"
                f"    os.remove({name_r})"
            )

        case Conditional(condition_file=condition_file,
                         then_branch=then_branch,
                         else_branch=else_branch):
            cond_r = repr(condition_file)
            # Body is compiled at fixed "    " relative indent — the outer
            # ind() call adds the actual indent level.
            then_code = _compile_nodes(then_branch, "    ")
            else_code = _compile_nodes(else_branch, "    ")
            block = (
                f"if os.path.exists({cond_r}):\n"
                f"{then_code}\n"
                f"else:\n"
                f"{else_code}"
            )
            return ind(block)
            pat_r = repr(pattern)
            return ind(
                f"import fnmatch as _fnmatch\n"
                f"_glob_result = sorted(f for f in os.listdir('.') "
                f"if os.path.isfile(f) and _fnmatch.fnmatch(f, {pat_r}))\n"
                f"sys.stdout.write(' '.join(_glob_result) if _glob_result else '(none)')"
            )

        case ForEachFile(glob_pattern=glob_pattern,
                         body_template=body_template,
                         placeholder=placeholder):
            pat_r = repr(glob_pattern)
            ph_r = repr(placeholder)
            inner_indent = indent + "    "
            lines = [
                f"import fnmatch as _fnmatch",
                f"_mk_files = sorted(f for f in os.listdir('.') "
                f"if os.path.isfile(f) and _fnmatch.fnmatch(f, {pat_r}))",
                f"for _mk_f in _mk_files:",
            ]
            for tmpl in body_template:
                code = _compile_node(tmpl, inner_indent)
                # Replace placeholder references in the generated Python code
                code = code.replace(placeholder, "' + _mk_f + '")
                lines.append(code)
            return '\n'.join(lines)

        case _:
            return ind("pass  # unknown node type")
