"""SQL backend — compile ASG nodes to SQL (SQLite).

ASG → SQL script. The generated SQL, when executed against an in-memory SQLite
database, produces the same observable output as direct execution through the
interpreter, shell backend, or Python backend.

Design decisions:
  - File → Table mapping: `notes.txt` → table `"notes.txt"` (double-quoted
    identifier, preserving dots — SQLite supports this, so file names map 1:1).
    A file is modeled as a table with a single `line` TEXT column, where each
    line of the file is a row. This preserves the line-oriented semantics of
    the interpreter.
  - CreateFile: CREATE TABLE + INSERT (one row for the content, which may
    contain embedded newlines → multi-row insert).
  - ReadFile: SELECT all lines, concatenated with spaces (matches interpreter
    semantics where newlines → spaces).
  - CountLines: SELECT COUNT(*).
  - AppendFile: INSERT new row.
  - SortLines: SELECT line ORDER BY line.
  - HeadLines: SELECT line LIMIT N.
  - SumNumbers: SELECT COALESCE(SUM(...), 0).
  - ExtractPattern: SELECT line WHERE line LIKE '%pattern%'.
  - CopyFile: CREATE TABLE dest AS SELECT * FROM source.
  - ListFiles: SELECT name FROM sqlite_master WHERE type='table'.
  - FindFiles: SELECT name FROM sqlite_master tables WHERE any row LIKE pattern.
  - DeleteFile: DROP TABLE.
  - MakeDirectory: SQL has no dirs — model as a no-op that succeeds silently.
    (A directory in the file world maps to a schema in SQL; we skip that here
    and just let subsequent table operations work.)
  - MoveFile: ALTER TABLE RENAME.
  - Conditional: implemented via temp tables / CASE logic in the executor.

Safety model (fail-CLOSED — matches interpreter and other backends):
  - CreateFile: CREATE TABLE fails if table exists (IF NOT EXISTS + check).
  - DeleteFile without confirm: output 'REFUSED', don't drop.
  - CopyFile/MoveFile: guard against existing dest table.

Execution model: the SQL script is run against an in-memory SQLite database.
The script uses SELECT to produce observable output (printed to stdout by
the SQLite CLI, or collected by the Python executor).
"""

from __future__ import annotations

import re
import sqlite3
from typing import Any

from asg import (
    ASGNode, CreateFile, ReadFile, AppendFile, CountLines, CopyFile,
    MakeDirectory, MoveFile, ListFiles, FindFiles, DeleteFile, Conditional,
    CountWords, SortLines, HeadLines, SumNumbers, ExtractPattern,
)


def _table_name(filename: str) -> str:
    """Convert a filename to a double-quoted SQL identifier.

    notes.txt → "notes.txt"  (dots preserved — SQLite supports quoted identifiers)
    data.csv  → "data.csv"

    The returned string includes the surrounding double-quotes, ready for
    direct interpolation into SQL DDL/DML statements.
    """
    escaped = filename.replace('"', '""')
    return f'"{escaped}"'


def _raw_name(filename: str) -> str:
    """Return the filename as stored in sqlite_master (unquoted)."""
    return filename.replace('""', '"')


def _sql_escape(s: str) -> str:
    """Escape a string for use in SQL single-quoted literals."""
    return s.replace("'", "''")


def compile_to_sql(nodes: list[ASGNode]) -> str:
    """Compile a list of ASG nodes into a SQL script string.

    The script can be executed against an in-memory SQLite database. Output
    is produced via SELECT statements that are collected as the 'stdout'.
    """
    lines = ["-- Auto-generated by sql_backend.compile_to_sql()",
             "-- Source: ASG → SQL (SQLite dialect)"]
    for node in nodes:
        stmts = _compile_node(node)
        lines.append(stmts)
    return '\n'.join(lines)


def _compile_node(node: ASGNode) -> str:
    """Compile a single ASG node to SQL statement(s)."""

    match node:

        case CreateFile(name=name, content=content):
            tbl = _table_name(name)
            raw = _raw_name(name)
            # Fail-closed: if table exists, output REFUSED
            # Split content into lines for line-oriented semantics
            content_lines = content.split('\n')
            values = ", ".join(f"('{_sql_escape(l)}')" for l in content_lines)
            return (
                f"-- CreateFile: {name}\n"
                f"SELECT CASE WHEN EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='{raw}')\n"
                f"  THEN 'REFUSED'\n"
                f"  ELSE ''\n"
                f"END AS _output_{raw.replace('.', '_')};\n"
                f"CREATE TABLE {tbl} (line TEXT);\n"
                f"INSERT INTO {tbl} (line) VALUES {values};"
            )

        case ReadFile(name=name):
            tbl = _table_name(name)
            raw = _raw_name(name)
            # Read all lines, join with spaces (matches interpreter: newlines → spaces)
            return (
                f"-- ReadFile: {name}\n"
                f"SELECT CASE WHEN EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='{raw}')\n"
                f"  THEN (SELECT group_concat(line, ' ') FROM {tbl})\n"
                f"  ELSE ''\n"
                f"END AS _output;"
            )

        case AppendFile(text=text, name=name):
            tbl = _table_name(name)
            return (
                f"-- AppendFile: {name}\n"
                f"INSERT INTO {tbl} (line) VALUES ('{_sql_escape(text)}');"
            )

        case CountLines(name=name):
            tbl = _table_name(name)
            raw = _raw_name(name)
            return (
                f"-- CountLines: {name}\n"
                f"SELECT CASE WHEN EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='{raw}')\n"
                f"  THEN CAST((SELECT COUNT(*) FROM {tbl}) AS TEXT)\n"
                f"  ELSE '0'\n"
                f"END AS _output;"
            )

        case CountWords(name=name):
            tbl = _table_name(name)
            raw = _raw_name(name)
            # Count words across all lines: split on whitespace
            return (
                f"-- CountWords: {name}\n"
                f"SELECT CASE WHEN EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='{raw}')\n"
                f"  THEN CAST((SELECT SUM(length(line) - length(replace(line, ' ', '')) + 1) FROM {tbl} WHERE line != '') AS TEXT)\n"
                f"  ELSE '0'\n"
                f"END AS _output;"
            )

        case SortLines(name=name):
            tbl = _table_name(name)
            raw = _raw_name(name)
            return (
                f"-- SortLines: {name}\n"
                f"SELECT CASE WHEN EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='{raw}')\n"
                f"  THEN (SELECT group_concat(line, ' ') FROM (SELECT line FROM {tbl} ORDER BY line))\n"
                f"  ELSE ''\n"
                f"END AS _output;"
            )

        case HeadLines(name=name, count=count):
            tbl = _table_name(name)
            raw = _raw_name(name)
            return (
                f"-- HeadLines: {name} (first {count})\n"
                f"SELECT CASE WHEN EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='{raw}')\n"
                f"  THEN (SELECT group_concat(line, ' ') FROM (SELECT line FROM {tbl} LIMIT {count}))\n"
                f"  ELSE ''\n"
                f"END AS _output;"
            )

        case SumNumbers(name=name):
            tbl = _table_name(name)
            raw = _raw_name(name)
            # Extract all integers from each line and sum them
            # SQLite doesn't have regex extraction; we store numbers per-line via a CTE
            # that splits on non-digit sequences. Simpler approach: iterate in Python executor.
            # For pure SQL, we use a trick: replace non-digits with spaces, trim, and sum.
            # But SQLite lacks easy regex. We'll handle this in the executor instead.
            return (
                f"-- SumNumbers: {name}\n"
                f"SELECT CASE WHEN EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='{raw}')\n"
                f"  THEN (SELECT group_concat(line, char(10)) FROM {tbl})\n"
                f"  ELSE ''\n"
                f"END AS _raw_lines;"
            )

        case ExtractPattern(name=name, pattern=pattern):
            tbl = _table_name(name)
            raw = _raw_name(name)
            return (
                f"-- ExtractPattern: {pattern} from {name}\n"
                f"SELECT CASE WHEN EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='{raw}')\n"
                f"  THEN COALESCE((SELECT group_concat(line, ' ') FROM {tbl} WHERE line LIKE '%{_sql_escape(pattern)}%'), '')\n"
                f"  ELSE ''\n"
                f"END AS _output;"
            )

        case CopyFile(source=source, dest=dest):
            src = _table_name(source)
            dst = _table_name(dest)
            src_raw = _raw_name(source)
            dst_raw = _raw_name(dest)
            return (
                f"-- CopyFile: {source} → {dest}\n"
                f"SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='{src_raw}')\n"
                f"  THEN 'REFUSED'\n"
                f"  WHEN EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='{dst_raw}')\n"
                f"  THEN 'REFUSED'\n"
                f"  ELSE ''\n"
                f"END AS _guard;\n"
                f"CREATE TABLE {dst} AS SELECT * FROM {src};"
            )

        case MakeDirectory(name=name):
            return f"-- MakeDirectory: {name} (no-op in SQL)"

        case MoveFile(source=source, dest=dest):
            src = _table_name(source)
            dst = _table_name(dest)
            src_raw = _raw_name(source)
            dst_raw = _raw_name(dest)
            return (
                f"-- MoveFile: {source} → {dest}\n"
                f"SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='{src_raw}')\n"
                f"  THEN 'REFUSED'\n"
                f"  WHEN EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='{dst_raw}')\n"
                f"  THEN 'REFUSED'\n"
                f"  ELSE ''\n"
                f"END AS _guard;\n"
                f"ALTER TABLE {src} RENAME TO {dst};"
            )

        case ListFiles(directory=directory):
            if directory == '.':
                return (
                    f"-- ListFiles: cwd\n"
                    f"SELECT name FROM sqlite_master WHERE type='table' "
                    f"AND name NOT LIKE 'sqlite_%' ORDER BY name;"
                )
            else:
                return (
                    f"-- ListFiles: {directory}\n"
                    f"SELECT 'NONE' AS _no_dir_support;"
                )

        case FindFiles(text=text):
            return (
                f"-- FindFiles: containing '{text}'\n"
                f"-- Requires per-table scan (done in executor)\n"
                f"SELECT name FROM sqlite_master WHERE type='table' "
                f"AND name NOT LIKE 'sqlite_%' ORDER BY name;"
            )

        case DeleteFile(name=name, confirm=confirm):
            tbl = _table_name(name)
            raw = _raw_name(name)
            if not confirm:
                return (
                    f"-- DeleteFile: {name} (REFUSED — no confirm)\n"
                    f"SELECT 'REFUSED' AS _output;"
                )
            return (
                f"-- DeleteFile: {name} (confirmed)\n"
                f"DROP TABLE IF EXISTS {tbl};"
            )

        case Conditional(condition_file=condition_file,
                         then_branch=then_branch,
                         else_branch=else_branch):
            raw = _raw_name(condition_file)
            then_sql = '\n'.join(_compile_node(n) for n in then_branch)
            else_sql = '\n'.join(_compile_node(n) for n in else_branch)
            return (
                f"-- Conditional: if {condition_file} exists\n"
                f"SELECT CASE WHEN EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='{raw}')\n"
                f"  THEN 'then'\n"
                f"  ELSE 'else'\n"
                f"END AS _branch;"
            )

        case _:
            return f"-- Unknown node type: {type(node).__name__}"


# ---------------------------------------------------------------------------
# Execution engine — compile + run against in-memory SQLite
# ---------------------------------------------------------------------------

def execute_sql(nodes: list[ASGNode]) -> str:
    """Compile ASG nodes to SQL, execute against in-memory SQLite, return stdout.

    This is the SQL backend's execution engine. It handles the semantic gaps
    between SQL and the file-oriented ASG nodes (e.g., SumNumbers needs
    Python-side integer extraction since SQLite lacks regex capture).

    Output matches the interpreter's observable stdout: the last meaningful
    output from a Terminal/Read operation.
    """
    conn = sqlite3.connect(':memory:')
    cursor = conn.cursor()
    output_parts = []

    for node in nodes:
        result = _execute_node(cursor, node, conn)
        if result is not None:
            output_parts.append(result)

    conn.close()
    return ' '.join(output_parts) if output_parts else ''


def _execute_node(cursor: sqlite3.Cursor, node: ASGNode, conn: sqlite3.Connection) -> str | None:
    """Execute a single ASG node against the SQLite database. Returns stdout or None."""

    def table_exists(raw: str) -> bool:
        cursor.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (raw,))
        return cursor.fetchone() is not None

    match node:

        case CreateFile(name=name, content=content):
            tbl = _table_name(name)
            raw = _raw_name(name)
            if table_exists(raw):
                return 'REFUSED'
            cursor.execute(f'CREATE TABLE {tbl} (line TEXT)')
            for line in content.split('\n'):
                cursor.execute(f'INSERT INTO {tbl} (line) VALUES (?)', (line,))
            conn.commit()
            return None

        case ReadFile(name=name):
            tbl = _table_name(name)
            raw = _raw_name(name)
            if not table_exists(raw):
                return None
            cursor.execute(f'SELECT line FROM {tbl}')
            rows = cursor.fetchall()
            return ' '.join(r[0] for r in rows) if rows else ''

        case AppendFile(text=text, name=name):
            tbl = _table_name(name)
            raw = _raw_name(name)
            if not table_exists(raw):
                return 'REFUSED'
            cursor.execute(f'INSERT INTO {tbl} (line) VALUES (?)', (text,))
            conn.commit()
            return None

        case CountLines(name=name):
            tbl = _table_name(name)
            raw = _raw_name(name)
            if not table_exists(raw):
                return '0'
            cursor.execute(f'SELECT COUNT(*) FROM {tbl}')
            return str(cursor.fetchone()[0])

        case CountWords(name=name):
            tbl = _table_name(name)
            raw = _raw_name(name)
            if not table_exists(raw):
                return '0'
            cursor.execute(f'SELECT line FROM {tbl}')
            rows = cursor.fetchall()
            word_count = sum(len((r[0] or '').split()) for r in rows)
            return str(word_count)

        case SortLines(name=name):
            tbl = _table_name(name)
            raw = _raw_name(name)
            if not table_exists(raw):
                return ''
            cursor.execute(f'SELECT line FROM {tbl} ORDER BY line')
            rows = cursor.fetchall()
            return ' '.join(r[0] for r in rows) if rows else ''

        case HeadLines(name=name, count=count):
            tbl = _table_name(name)
            raw = _raw_name(name)
            if not table_exists(raw):
                return ''
            cursor.execute(f'SELECT line FROM {tbl} LIMIT ?', (count,))
            rows = cursor.fetchall()
            return ' '.join(r[0] for r in rows) if rows else ''

        case SumNumbers(name=name):
            tbl = _table_name(name)
            raw = _raw_name(name)
            if not table_exists(raw):
                return '0'
            cursor.execute(f'SELECT line FROM {tbl}')
            rows = cursor.fetchall()
            total = 0
            for r in rows:
                total += sum(int(x) for x in re.findall(r'\d+', r[0] or ''))
            return str(total)

        case ExtractPattern(name=name, pattern=pattern):
            tbl = _table_name(name)
            raw = _raw_name(name)
            if not table_exists(raw):
                return ''
            cursor.execute(f'SELECT line FROM {tbl} WHERE line LIKE ?', (f'%{pattern}%',))
            rows = cursor.fetchall()
            return ' '.join(r[0] for r in rows) if rows else ''

        case CopyFile(source=source, dest=dest):
            src = _table_name(source)
            dst = _table_name(dest)
            src_raw = _raw_name(source)
            dst_raw = _raw_name(dest)
            if not table_exists(src_raw) or table_exists(dst_raw):
                return 'REFUSED'
            cursor.execute(f'CREATE TABLE {dst} AS SELECT * FROM {src}')
            conn.commit()
            return None

        case MakeDirectory(name=name):
            # No-op in SQL (no directory concept)
            return None

        case MoveFile(source=source, dest=dest):
            src = _table_name(source)
            dst = _table_name(dest)
            src_raw = _raw_name(source)
            dst_raw = _raw_name(dest)
            if not table_exists(src_raw) or table_exists(dst_raw):
                return 'REFUSED'
            cursor.execute(f'ALTER TABLE {src} RENAME TO {dst}')
            conn.commit()
            return None

        case ListFiles(directory=directory):
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='table' "
                "AND name NOT LIKE 'sqlite_%' ORDER BY name"
            )
            rows = cursor.fetchall()
            tables = [r[0] for r in rows]
            return ' '.join(tables) if tables else '(empty)'

        case FindFiles(text=text):
            # Find tables that have any row containing the text
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='table' "
                "AND name NOT LIKE 'sqlite_%' ORDER BY name"
            )
            all_tables = [r[0] for r in cursor.fetchall()]
            matching = []
            for tbl_raw in all_tables:
                tbl_q = _table_name(tbl_raw)
                cursor.execute(f'SELECT COUNT(*) FROM {tbl_q} WHERE line LIKE ?', (f'%{text}%',))
                if cursor.fetchone()[0] > 0:
                    matching.append(tbl_raw)
            return ' '.join(matching) if matching else '(empty)'

        case DeleteFile(name=name, confirm=confirm):
            tbl = _table_name(name)
            if not confirm:
                return 'REFUSED'
            cursor.execute(f'DROP TABLE IF EXISTS {tbl}')
            conn.commit()
            return None

        case Conditional(condition_file=condition_file, then_branch=then_branch, else_branch=else_branch):
            raw = _raw_name(condition_file)
            if table_exists(raw):
                results = []
                for n in then_branch:
                    r = _execute_node(cursor, n, conn)
                    if r is not None:
                        results.append(r)
                return ' '.join(results) if results else None
            else:
                results = []
                for n in else_branch:
                    r = _execute_node(cursor, n, conn)
                    if r is not None:
                        results.append(r)
                return ' '.join(results) if results else None

        case _:
            return None
